export const lightColorVars = {
    "--k-color-0": "var(--k-color-gray-9) !important",
    "--k-color-1": "var(--k-color-gray-8) !important",
    "--k-color-2": "var(--k-color-gray-7) !important",
    "--k-color-3": "var(--k-color-gray-6) !important",
    "--k-color-4": "var(--k-color-gray-5) !important",
    "--k-color-5": "var(--k-color-gray-4) !important",
    "--k-color-6": "var(--k-color-gray-3) !important",
    "--k-color-7": "var(--k-color-gray-2) !important",
    "--k-color-8": "var(--k-color-gray-1) !important",
    "--k-color-9": "var(--k-color-gray-0) !important",

    "--k-bgcolor-0": "var(--k-color-gray-0) !important",
    "--k-bgcolor-1": "var(--k-color-gray-1) !important",
    "--k-bgcolor-2": "var(--k-color-gray-2) !important",
    "--k-bgcolor-3": "var(--k-color-gray-3) !important",
    "--k-bgcolor-4": "var(--k-color-gray-4) !important",
    "--k-bgcolor-5": "var(--k-color-gray-5) !important",
    "--k-bgcolor-6": "var(--k-color-gray-6) !important",
    "--k-bgcolor-7": "var(--k-color-gray-7) !important",
    "--k-bgcolor-8": "var(--k-color-gray-8) !important",
    "--k-bgcolor-9": "var(--k-color-gray-9) !important",
};
export const lightColorizedColorVars = {
    "--k-color": "var(--k-color-gray-9) !important",
    "--k-color-1": "var(--k-color-gray-8) !important",
    "--k-color-2": "var(--k-color-gray-7) !important",
    "--k-color-3": "var(--k-color-gray-6) !important",
    "--k-color-4": "var(--k-color-gray-5) !important",
    "--k-color-5": "var(--k-color-gray-4) !important",
    "--k-color-6": "var(--k-color-gray-3) !important",
    "--k-color-7": "var(--k-color-gray-2) !important",
    "--k-color-8": "var(--k-color-gray-1) !important",
    "--k-color-9": "var(--k-color-gray-0) !important",

    "--k-bgcolor": "var(--k-color-gray-0) !important",
    "--k-bgcolor-1": "var(--k-color-gray-1) !important",
    "--k-bgcolor-2": "var(--k-color-gray-2) !important",
    "--k-bgcolor-3": "var(--k-color-gray-3) !important",
    "--k-bgcolor-4": "var(--k-color-gray-4) !important",
    "--k-bgcolor-5": "var(--k-color-gray-5) !important",
    "--k-bgcolor-6": "var(--k-color-gray-6) !important",
    "--k-bgcolor-7": "var(--k-color-gray-7) !important",
    "--k-bgcolor-8": "var(--k-color-gray-8) !important",
    "--k-bgcolor-9": "var(--k-color-gray-9) !important",
};
