export const lightColorVars = {
    "--k-color-0": "var(--k-color-gray-9)",
    "--k-color-1": "var(--k-color-gray-8)",
    "--k-color-2": "var(--k-color-gray-7)",
    "--k-color-3": "var(--k-color-gray-6)",
    "--k-color-4": "var(--k-color-gray-5)",
    "--k-color-5": "var(--k-color-gray-4)",
    "--k-color-6": "var(--k-color-gray-3)",
    "--k-color-7": "var(--k-color-gray-2)",
    "--k-color-8": "var(--k-color-gray-1)",
    "--k-color-9": "var(--k-color-gray-0)",

    "--k-bgcolor-0": "var(--k-color-gray-0)",
    "--k-bgcolor-1": "var(--k-color-gray-1)",
    "--k-bgcolor-2": "var(--k-color-gray-2)",
    "--k-bgcolor-3": "var(--k-color-gray-3)",
    "--k-bgcolor-4": "var(--k-color-gray-4)",
    "--k-bgcolor-5": "var(--k-color-gray-5)",
    "--k-bgcolor-6": "var(--k-color-gray-6)",
    "--k-bgcolor-7": "var(--k-color-gray-7)",
    "--k-bgcolor-8": "var(--k-color-gray-8)",
    "--k-bgcolor-9": "var(--k-color-gray-9)",
};
export const lightColorizedColorVars = {
    "--k-color-0": "var(--k-color-gray-9)",
    "--k-color-1": "var(--k-color-gray-8)",
    "--k-color-2": "var(--k-color-gray-7)",
    "--k-color-3": "var(--k-color-gray-6)",
    "--k-color-4": "var(--k-color-gray-5)",
    "--k-color-5": "var(--k-color-gray-4)",
    "--k-color-6": "var(--k-color-gray-3)",
    "--k-color-7": "var(--k-color-gray-2)",
    "--k-color-8": "var(--k-color-gray-1)",
    "--k-color-9": "var(--k-color-gray-0)",

    "--k-bgcolor-0": "var(--k-color-gray-0)",
    "--k-bgcolor-1": "var(--k-color-gray-1)",
    "--k-bgcolor-2": "var(--k-color-gray-2)",
    "--k-bgcolor-3": "var(--k-color-gray-3)",
    "--k-bgcolor-4": "var(--k-color-gray-4)",
    "--k-bgcolor-5": "var(--k-color-gray-5)",
    "--k-bgcolor-6": "var(--k-color-gray-6)",
    "--k-bgcolor-7": "var(--k-color-gray-7)",
    "--k-bgcolor-8": "var(--k-color-gray-8)",
    "--k-bgcolor-9": "var(--k-color-gray-9)",
};
